"""admin roles, verification workflow, documents, test orders, issues

Revision ID: 90d34581d31f
Revises: d0994368588c
Create Date: 2026-09-17 19:36:25.774038
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '90d34581d31f'
down_revision: Union[str, None] = 'd0994368588c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rider_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rider_id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.String(length=48), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('submitted', 'accepted', 'rejected', name='documentstatus', native_enum=False), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['rider_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rider_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rider_documents_doc_type'), ['doc_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_rider_documents_rider_id'), ['rider_id'], unique=False)

    op.create_table('delivery_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delivery_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('rider_id', sa.Integer(), nullable=False),
    sa.Column('issue_type', sa.String(length=48), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('open', 'acknowledged', 'resolved', name='deliveryissuestatus', native_enum=False), nullable=False),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('resolved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rider_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('delivery_issues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_delivery_issues_delivery_id'), ['delivery_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_delivery_issues_issue_type'), ['issue_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_delivery_issues_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_delivery_issues_rider_id'), ['rider_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_delivery_issues_status'), ['status'], unique=False)

    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_type', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('target_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reason', sa.Text(), nullable=True))

    with op.batch_alter_table('messes', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('is_test', sa.Boolean(), nullable=False, server_default=sa.false())
        )
        batch_op.create_index(batch_op.f('ix_messes_is_test'), ['is_test'], unique=False)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('is_test', sa.Boolean(), nullable=False, server_default=sa.false())
        )
        batch_op.add_column(sa.Column('test_note', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_orders_is_test'), ['is_test'], unique=False)

    with op.batch_alter_table('rider_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('correction_reason', sa.String(length=500), nullable=True))
        batch_op.alter_column('approval_status',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('draft', 'pending', 'submitted', 'under_review', 'approved', 'rejected', 'needs_correction', name='approvalstatus', native_enum=False),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_role', sa.Enum('super_admin', 'partner_verification', 'operations', 'support', name='adminrole', native_enum=False), nullable=True))
        batch_op.add_column(sa.Column('suspended_reason', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('suspended_reason')
        batch_op.drop_column('admin_role')

    with op.batch_alter_table('rider_profiles', schema=None) as batch_op:
        batch_op.alter_column('approval_status',
               existing_type=sa.Enum('draft', 'pending', 'submitted', 'under_review', 'approved', 'rejected', 'needs_correction', name='approvalstatus', native_enum=False),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)
        batch_op.drop_column('correction_reason')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_is_test'))
        batch_op.drop_column('test_note')
        batch_op.drop_column('is_test')

    with op.batch_alter_table('messes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messes_is_test'))
        batch_op.drop_column('is_test')

    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_column('reason')
        batch_op.drop_column('target_id')
        batch_op.drop_column('target_type')

    with op.batch_alter_table('delivery_issues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_delivery_issues_status'))
        batch_op.drop_index(batch_op.f('ix_delivery_issues_rider_id'))
        batch_op.drop_index(batch_op.f('ix_delivery_issues_order_id'))
        batch_op.drop_index(batch_op.f('ix_delivery_issues_issue_type'))
        batch_op.drop_index(batch_op.f('ix_delivery_issues_delivery_id'))

    op.drop_table('delivery_issues')
    with op.batch_alter_table('rider_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rider_documents_rider_id'))
        batch_op.drop_index(batch_op.f('ix_rider_documents_doc_type'))

    op.drop_table('rider_documents')
    # ### end Alembic commands ###
