"""phone otp auth

Revision ID: d0994368588c
Revises: 39c0b31fd0a3
Create Date: 2026-09-15 18:23:55.327809
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd0994368588c'
down_revision: Union[str, None] = '39c0b31fd0a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_otps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('consumed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_otps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_otps_phone'), ['phone'], unique=False)

    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('pending', 'offered', 'accepted', 'en_route_to_mess', 'picked_up', 'delivering', 'delivered', 'cancelled', name='deliverystatus', native_enum=False),
               existing_nullable=False)
        batch_op.alter_column('payout_status',
               existing_type=sa.VARCHAR(length=12),
               type_=sa.Enum('pending', 'paid', name='payoutstatus', native_enum=False),
               existing_nullable=False)

    with op.batch_alter_table('delivery_batches', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Enum('open', 'offered', 'assigned', 'picked_up', 'completed', 'cancelled', name='batchstatus', native_enum=False),
               existing_nullable=False)

    with op.batch_alter_table('delivery_offers', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=12),
               type_=sa.Enum('sent', 'accepted', 'rejected', 'expired', name='offerstatus', native_enum=False),
               existing_nullable=False)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=24),
               type_=sa.Enum('placed', 'accepted', 'preparing', 'ready', 'assigned', 'picked_up', 'out_for_delivery', 'delivered', 'cancelled', name='orderstatus', native_enum=False),
               existing_nullable=False)
        batch_op.alter_column('payment_status',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Enum('pending', 'paid', 'failed', 'refunded', name='paymentstatus', native_enum=False),
               existing_nullable=False)

    with op.batch_alter_table('rider_profiles', schema=None) as batch_op:
        batch_op.alter_column('approval_status',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Enum('pending', 'approved', 'rejected', name='approvalstatus', native_enum=False),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_users_phone'), ['phone'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_phone'))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('rider_profiles', schema=None) as batch_op:
        batch_op.alter_column('approval_status',
               existing_type=sa.Enum('pending', 'approved', 'rejected', name='approvalstatus', native_enum=False),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('payment_status',
               existing_type=sa.Enum('pending', 'paid', 'failed', 'refunded', name='paymentstatus', native_enum=False),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.Enum('placed', 'accepted', 'preparing', 'ready', 'assigned', 'picked_up', 'out_for_delivery', 'delivered', 'cancelled', name='orderstatus', native_enum=False),
               type_=sa.VARCHAR(length=24),
               existing_nullable=False)

    with op.batch_alter_table('delivery_offers', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('sent', 'accepted', 'rejected', 'expired', name='offerstatus', native_enum=False),
               type_=sa.VARCHAR(length=12),
               existing_nullable=False)

    with op.batch_alter_table('delivery_batches', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('open', 'offered', 'assigned', 'picked_up', 'completed', 'cancelled', name='batchstatus', native_enum=False),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)

    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.alter_column('payout_status',
               existing_type=sa.Enum('pending', 'paid', name='payoutstatus', native_enum=False),
               type_=sa.VARCHAR(length=12),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.Enum('pending', 'offered', 'accepted', 'en_route_to_mess', 'picked_up', 'delivering', 'delivered', 'cancelled', name='deliverystatus', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('login_otps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_otps_phone'))

    op.drop_table('login_otps')
    # ### end Alembic commands ###
